"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.S = exports.Z = exports.Nil = exports.Cell = exports.Nothing = exports.Just = exports.Right = exports.Left = exports.Pair = undefined;

var _systemfj = require("./systemfj");

// some standard types - exposing constructors right away
// THIS SHOULD GO TO Type creation function - just add the names to Exports!!!
var Pair = exports.Pair = new _systemfj.Type("Pair a b", "Pair a b").Pair;

//p = Pair 1, 2
// Generated by CoffeeScript 2.0.1
var Left = exports.Left = new _systemfj.Type("Either a b", "Left a", "Right b").Left;

var Right = exports.Right = _systemfj.Type.Either.Right;

var Just = exports.Just = new _systemfj.Type("Maybe a", "Just a", "Nothing").Just;

var Nothing = exports.Nothing = _systemfj.Type.Maybe.Nothing;

var Cell = exports.Cell = new _systemfj.Type("List a", "Cell a List", "Nil").Cell;

var Nil = exports.Nil = _systemfj.Type.List.Nil;

var Z = exports.Z = new _systemfj.Type("Nat", "Z", "S Nat").Z;

var S = exports.S = _systemfj.Type.Nat.S;