'use strict';

var _systemfj = require('./systemfj');

var _base = require('./base');

// Generated by CoffeeScript 2.0.1
var T, length, tCustom;

// Some tests #################################################
T = _systemfj.Type;

tCustom = new _systemfj.Type("Custom", "Cons Float String");

//console.log t for t in Type.showAllTypes()
length = new _systemfj.Func("length");

length.match("Nil", function () {
  return 0;
});

length.match("Cell", function (x) {
  return 1 + length.ap(tail(x));
});

//_id = new Func "id"

//console.log f1.show()
//console.dir Maybe, {depth: 4, colors: true}
//console.dir List, {depth: 4, colors: true}
//console.dir Type, {depth: 6, colors: true}

//t1 = T.Custom.Cons 2, "Hello"
//console.log t1.show()

//console.log T.List.constructors.Cell.show()
//console.log T.List.show()