// Generated by CoffeeScript 2.0.1
import {
  Type,
  Constructor,
  Value,
  Func,
  Var,
  TypeVar
} from './systemfj';

// some standard types - exposing constructors right away
// THIS SHOULD GO TO Type creation function - just add the names to Exports!!!
export var Pair = (new Type("Pair a b", "Pair a b")).Pair;

//p = Pair 1, 2
export var Left = (new Type("Either a b", "Left a", "Right b")).Left;

export var Right = Type.Either.Right;

export var Just = (new Type("Maybe a", "Just a", "Nothing")).Just;

export var Nothing = Type.Maybe.Nothing;

export var Cell = (new Type("List a", "Cell a List", "Nil")).Cell;

export var Nil = Type.List.Nil;

export var Z = (new Type("Nat", "Z", "S Nat")).Z;

export var S = Type.Nat.S;
