// Generated by CoffeeScript 2.0.1
import {
  Type,
  Constructor,
  Value,
  Func,
  Var,
  TypeVar
} from './systemfj';

// some standard types - exposing constructors right away
// THIS SHOULD GO TO Type creation function - just add the names to Exports!!!
