// Generated by CoffeeScript 1.12.7
export var Logger = (function() {
  function Logger() {}

  Logger.OFF = 0;

  Logger.FATAL = 1;

  Logger.ERROR = 2;

  Logger.INFO = 3;

  Logger.VERBOSE = 4;

  Logger.DEBUG = 5;

  return Logger;

})();
