// Generated by CoffeeScript 2.0.1
var T, i, len, length, ref, t, t1, tCustom;

import {
  Type,
  Constructor,
  Value,
  Func,
  Var,
  TypeVar
} from './systemfj';

import {
  S,
  Z
} from './base';

// Some tests #################################################
T = Type;

tCustom = new Type("Custom", "Cons Float String");

ref = Type.showAllTypes();
for (i = 0, len = ref.length; i < len; i++) {
  t = ref[i];
  console.log(t);
}

length = new Func("length");

length.match("Nil", function() {
  return 0;
});

length.match("Cell", function(x) {
  return 1 + length.ap(tail(x));
});

//_id = new Func "id"

//console.log f1.show()
//console.dir Maybe, {depth: 4, colors: true}
//console.dir List, {depth: 4, colors: true}
//console.dir Type, {depth: 6, colors: true}
t1 = T.Custom.Cons(2, "Hello");

console.log(t1.show());

//console.log T.List.constructors.Cell.show()
//console.log T.List.show()
